[UI]
	#Photographer name will be shown in Photograph's tooltip.
	PhotographPhotographerNameTooltip = false
	#'Use while sneaking to open' message will be shown in Camera item tooltip.
	CameraSneakOpenTooltip = true
	#Crosshair will not get in the way when holding a photograph.
	PhotographInHandHideCrosshair = true
	#Tooltips for Developing Film Rolls and Copying Photographs will be shown on Film Rolls and Photographs respectively, describing the crafting recipe. 
	#Only when JEI is not installed. (Only JEI shows these recipes, not REI or EMI)
	RecipeTooltipsWithoutJei = true

	[UI.Viewfinder]
		FontSecondaryColorHex = "FF7A736C"
		BackgroundColorHex = "FA1F1D1B"
		#Mouse sensitivity modifier per 5 degrees of fov. Set to 0 to disable sensitivity changes.
		#Range: 0.0 ~ 1.0
		ZoomSensitivityModifier = 0.048
		FontMainColorHex = "FF2B2622"
[Capture]
	#Delay in ticks before capturing an image when shooting with flash.
	#If you experience flash synchronization issues (Flash having no effect on the image) - try increasing the value.
	#Range: 1 ~ 6
	FlashCaptureDelayTicks = 3
[FileSaving]
	#When saving, exposures will be organized into a folders corresponding to current world name.
	WorldNameSubfolder = true
	#When the Photograph is viewed in UI, image will be saved to 'exposures' folder as a png.
	SavePhotographs = true
